### ISSUE TITLE
Mined balance not shown

### ISSUE THREAD

**Issue by FarhadYazdi** [MetacoSA/QBitNinja#102]
Balance of addresses with mined block is not correct
http://api.qbit.ninja/balances/1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa/summary
shows -> "amount": 1809533767 but final balance is 68.10533767BTC, mined BTC not showing

and
http://api.qbit.ninja/balances/1CK6KHY6MHgYvmRQ4PAafKYDrg1ejbH1cE/summary
return 504 error : Gateway Timeout

**Comment by NicolasDorier** [comment]
shit I may have broken something in my last update...

**Comment by NicolasDorier** [comment]
The balance is correct http://api.qbit.ninja/balances/1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa/summary matches with https://blockstream.info/address/1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa

**Comment by NicolasDorier** [comment]
Block explorer not reporting the same balance are wrong. 1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa should only show P2PKH payment, not P2PK.

**Comment by NicolasDorier** [comment]
For the timeout, this is a limitation of qbit ninja, it is difficult for it to calculate the balance summary for really big addresses.
