### ISSUE TITLE
Balance issue

### ISSUE THREAD

**Issue by ArtjomP** [MetacoSA/QBitNinja#105]
Hello there!
I got a balance issue from yesterday.
```cs
var network = Network.Main;
var client = new QBitNinjaClient(network);
var destination = BitcoinAddress.Create("1911V1aepiPWZxVKghp9jV9JwvUAhH1enp", network);
var balanceModel = await client.GetBalance(destination, true);
```
And I get 
balanceModel.Operations.Count == 0
But actually:
[balance](https://btc.com/1911V1aepiPWZxVKghp9jV9JwvUAhH1enp)

Could you help me, please?

Thank you in advance!

**Comment by NicolasDorier** [comment]
@ArtjomP yestersday I  swtich the storage because I reindexed the whole chain so we pay less.
Sadly, it seems there is an issue in the indexation, I won't be able to fix it quick but checking it.

**Comment by ArtjomP** [comment]
Thank you!
If I can help you somehow you can count on me.

**Comment by NicolasDorier** [comment]
@ArtjomP so we stopped indexing properly from block 539,700. I will fix this, but because it is very very slow to sync, it might take 3 or 4 days to go back to normal.

**Comment by NicolasDorier** [comment]
@Bassist067  Check the docs in NBXplorer project. You also have some `sample_tests` in the project you can take a look  to.

**Comment by bitcoinbrisbane** [comment]
Thanks @NicolasDorier, this guy `https://api.qbit.ninja/balances/1Gpwq53eau1AyNADgpBrNJW6p1yE4Px8VX` has the same issue :(

**Comment by pda1989** [comment]
Hi, @NicolasDorier! 
How the sync is going, how long approximately left to wait?

**Comment by GnineWheel** [comment]
Still in sync?

**Comment by bitcoinbrisbane** [comment]
yay, mine has now synced!

**Comment by zeuspay** [comment]
Hello, @NicolasDorier!
I see some of you say it can be used, but I can't do it here. Is it not completely good yet? Please let me know if you understand. Thank you.

**Comment by bitcoinbrisbane** [comment]
@zeuspay seem to be up to July 2019

**Comment by zeuspay** [comment]
@bitcoinbrisbane What do you mean?

**Comment by NicolasDorier** [comment]
Almost done, still like 10K blocks.

**Comment by bitcoinbrisbane** [comment]
> @bitcoinbrisbane What do you mean?

Ive monitoring old addresses.  An address first seen in July started working :)

**Comment by bitcoinbrisbane** [comment]
> Almost done, still like 10K blocks. Sorry for that. :(

Awesome!  I've done a lot of refactoring to use NBXplorer.  Be a shame to see QBitNinja die.  Perhaps we could mirror?

**Comment by NicolasDorier** [comment]
@bitcoinbrisbane it won't die, it is quite low maintainance, the storage is expensive but I guess we can keep it up.

**Comment by bitcoinbrisbane** [comment]
More than happy to tip a few sats!

**Comment by NicolasDorier** [comment]
I would advise you to self-host qbitninja so that it is faster for you and it does not break if I do a bad update. But the main server will still be here.

**Comment by littleAnarchy** [comment]
Synchronizing stopped on 592299 block.

**Comment by NicolasDorier** [comment]
@littleAnarchy no it did not, normally it is now fully synched.

**Comment by bozhday** [comment]
Nicolas, It is very likely that not all the data entered the index. Example:

https://api.qbit.ninja/balances/1DhdEJBtYcWjuvhnDhmcGD492EB2Ce3JDW
Last tran: 7d43b68ba27023752070c3aa0f900fd5d62f4813615772e9468a39e9af4487d0 from 2019-09-09T08:25:45+00:00

https://www.blockchain.com/btc/address/1DhdEJBtYcWjuvhnDhmcGD492EB2Ce3JDW
Last tran: 06ebc9d9654a42470b1ec23596dc3a6ec11aeb03370111be8a633587d482ecd7 from 2019-09-16 10:26:51

**Comment by zeuspay** [comment]
@NicolasDorier 
Hello, I have successfully operated the coin this morning, but I can’t use it in the afternoon.

**Comment by NicolasDorier** [comment]
@bozhday it seems you are right. I will fix it tomorrow, maybe missing a few last blocks. Unsure why it did happen though.

**Comment by NicolasDorier** [comment]
@bozhday @zeuspay it is synching the last blocks, should be back in normal in a few hours.

**Comment by bozhday** [comment]
Nicolars, excellent work, thank you!

**Comment by NicolasDorier** [comment]
Can I close that everybody is good now?

**Comment by bitcoinbrisbane** [comment]
> Can I close that everybody is good now?

Working for me
