### ISSUE TITLE
Not found tran

### ISSUE THREAD

**Issue by bozhday** [MetacoSA/QBitNinja#107]
Nicolas, Hi!

https://blockchair.com/bitcoin/address/1Aim7is9dgMYfmjs2KAHqBXoLU9HyL8YFG
last tran is 2019-10-31 16:06

https://api.qbit.ninja/balances/1Aim7is9dgMYfmjs2KAHqBXoLU9HyL8YFG
last tran is 2019-10-21 08:45:26

Where could the problem be?
Thank you!

**Comment by bozhday** [comment]
I'm sorry, the data appeared after 8 hours.

**Comment by NicolasDorier** [comment]
So I can close this?
