### ISSUE TITLE
whats wrong with api.qbit.ninja

### ISSUE THREAD

**Issue by ragekillen** [MetacoSA/QBitNinja#108]
```
var client = new QBitNinjaClient("http://api.qbit.ninja/", Network.Main);

var balanceModel = await client.GetBalance("3BvV9TgmiN8UEtwdE6Uk893GiaAYsibZLn", false);
     if (balanceModel.Operations.Count > 0)
     {
           MessageBox.Show(balanceModel.Operations.Count.ToString());
     }
           MessageBox.Show(balanceModel.Operations.Count.ToString());
```

this returns 0 as the balance

but going to here
[http://api.qbit.ninja/balances/3BvV9TgmiN8UEtwdE6Uk893GiaAYsibZLn?unspentOnly=true](url)

we can see 1 result with the amount being 1350000

**Comment by NicolasDorier** [comment]
probably a bug on your side:
No problem on the restuls

https://api.qbit.ninja/balances/3BvV9TgmiN8UEtwdE6Uk893GiaAYsibZLn/summary
https://api.qbit.ninja/balances/3BvV9TgmiN8UEtwdE6Uk893GiaAYsibZLn?unspentOnly=true
https://blockstream.info/address/3BvV9TgmiN8UEtwdE6Uk893GiaAYsibZLn
