### ISSUE TITLE
Azure

### ISSUE THREAD

**Issue by muteddisk** [MetacoSA/QBitNinja#111]
Why do I need an account on azure to store the data that could be saved in a local SQL server? I don't see why I need to spend money for an azure account to get this piece of shit to work.

This is what to open source when microsoft is buying the platform

**Comment by NicolasDorier** [comment]
This is a full block explorer, most project don't need it. This is too coupled to Azure to run on anything else for performance reason.

Use https://github.com/dgarage/NBXplorer instead which is lightweight and no cloud dependency.
