### ISSUE TITLE
Nbitcoin(testnet), Qbitninja.client, spend your coin

### ISSUE THREAD

**Issue by jole95** [MetacoSA/QBitNinja#113]
### Nbitcoin-testnet-qbitninja (transactions)
Hi, 
I use Nbitcoin and Qbitninja. I read documentation on : [Spend your coin](https://programmingblockchain.gitbook.io/programmingblockchain/bitcoin_transfer/spend_your_coin)

`var bitcoinPrivateKey = new BitcoinSecret("**cRcYJLyX4spkbLRi7DQLUvcfk75XbVGNkFEQuFaBow3DuDUuuXX6**", Network.Testnet);
var network = bitcoinPrivateKey.Network;
var address = bitcoinPrivateKey.GetAddress();

Console.WriteLine(bitcoinPrivateKey);
Console.WriteLine(address); 
``var client = new QBitNinjaClient(network);
var transactionId = uint256.Parse(" **fc4277895a0ed104b505c44a194aff0b37b241b668cd4a2b93945b481bafc606**");
var **transactionResponse** = client.GetTransaction(transactionId).Result;

Console.WriteLine(transactionResponse.TransactionId); // null
Console.WriteLine(transactionResponse.Block.Confirmations); // **block is null**

**Thanks everyone**

I hope someone will be able to help me as I need to do this for my **graduate work**

`

**Comment by NicolasDorier** [comment]
I am starting again the testnet server, let me know and reopen if it keep crashing in a day.
