### ISSUE TITLE
Issue with QBitNinja and Unity Android Build

### ISSUE THREAD

**Issue by andygruening** [MetacoSA/QBitNinja#114]
Hey,
I was implementing QBitNinja and NBitcoin as dll‘s into my Unity project (The dll‘s are from an asset from
the asset store).
For being in the unity editor on windows it all works really fine, but when I make an android build, it cannot get the current balance of a private key with the QBitNinjaClient and it gives me the error „There are one or more errors“ (good to know). The projects scripting runtime is .NET 4.x Equivalent and the API compability level is Netstandard 2.0, just as it should be. I am also installing the NBitcoin dll through the NuGet console in visual studio seperately.
I have also tested multiple builds with the unity versions 2019.2 and 2018.4.
But the asset gave me an old version of NBitcoin, version 4.1, but that should not be a problem as it doesnt happen on windows.
Is there a minimum compatible android version? I have tested it with an phone running Android 5.1

I hope someone has more ideas and can help me, thanks!

**Comment by NicolasDorier** [comment]
It is possible that those are way outdated.
I will try to update the QBitNinja library, however I can't create unity asset stuff.

**Comment by NicolasDorier** [comment]
I just pushed 1.0.3.51 which should work with the latest version of NBitcoin. Let me know if there is any issue.

**Comment by NicolasDorier** [comment]
Please reopen if any problem.
