### ISSUE TITLE
Hosting QBit.Ninja inside docker

### ISSUE THREAD

**Issue by bijakatlykkex** [MetacoSA/QBitNinja#16]
We want to create docker containers hosting QBit.Ninja. But it seems we have shared resources here, like a- service bus and 2- Table storage

Is it safe to share these resources specifically the service bus?

Will we have performance increase by having multiple instances of QBit.Ninja running using the same table storage?

Thanks

**Comment by NicolasDorier** [comment]
if you have multiple instance of QBitNinja then you have higher availability, not higher performance.

Sharing ressources should not be an issue. (for initial indexing, you have a special command line for parallelizing the indexing)

**Comment by bijakatlykkex** [comment]
Thanks for clarification.
