### ISSUE TITLE
Unconfirmed transaction is not forgotten

### ISSUE THREAD

**Issue by bijakatlykkex** [MetacoSA/QBitNinja#18]
Hello,

As I understand of what discussed in https://github.com/MetacoSA/QBitNinja/issues/8 , unconfirmed transactions is forgotten after some hours (6 I think). For the transaction f5b05118d0a51bcedfeae1b37dfea165f835290ce9668c276b681ed0bb6b4976 although it has been past more than a day from its submission (https://www.blocktrail.com/BTC/tx/f5b05118d0a51bcedfeae1b37dfea165f835290ce9668c276b681ed0bb6b4976) it is still available (http://web.archive.org/web/20170311122658/http://api.qbit.ninja/transactions/f5b05118d0a51bcedfeae1b37dfea165f835290ce9668c276b681ed0bb6b4976?colored=true).

Is it a problem? (This transaction seems to be related to the recent malleability attack on Bitcoin network)

Thanks

**Comment by NicolasDorier** [comment]
A transaction is never forgotten. The transaction is sent to the whole network and every node have different mempool policy. It will just be never confirmed.

What we mean by "forgotten" is when a transaction has too low fee to get confirmed, we need to wait that most of the node forget about it, so another transaction that double spend the same input with better fees can go through.

**Comment by bijakatlykkex** [comment]
Thanks for the allocated time.

My concern is about QBit.Ninja behavior besides what happens in Bitcoin network. My question is because I thought there may be some special behavior regarding unconfirmed transactions in QBit.Ninja itself.

**Comment by NicolasDorier** [comment]
QBitNinja indeed does not show an unconfirmed in the balance of an address after 1 day.

**Comment by bijakatlykkex** [comment]
Thanks for clarification.
