### ISSUE TITLE
Support of blocks more than 1 MB

### ISSUE THREAD

**Issue by bijakatlykkex** [MetacoSA/QBitNinja#21]
Hello,

Is there any limitation in Indexer or QBit.Ninja regarding blocks more than 1 MB?

I am considering the use of Bitcoin Unlimited instead Bitcoin Core in some deployments, and worrying if possible blocks more than 1 MB will cause any problems.

Thanks

**Comment by NicolasDorier** [comment]
hey. I don't know as it is not tested.

NBitcoin by itself have various DDOS protection mechanism which will prevent oversized blocks. (Not sure how much, maybe 5MB)

Indexing a whole block takes currently lots of time (I think around 30 seconds), which mean that  even if you get around NBitcoin limits, QBitNinja would stop being able to index faster than the network can produce blocks.

**Comment by NicolasDorier** [comment]
Just checked, NBitcoin will limit you to 33554432 bytes (32MB)

**Comment by bijakatlykkex** [comment]
I was able to generate and index and somehow verify transactions of a block about 16 MB (a little bit smaller), using the Bitcoin Unlimited (regtest mode) + QBit.Ninja + Indexer.Console.

So it seems the stack is working for large blocks.

Thanks very much for contributions and update.

**Comment by NicolasDorier** [comment]
@bijakatlykkex have you checked how much time it takes to index balance/transaction/blocks on it ? I am interested to know as well.

**Comment by bijakatlykkex** [comment]
The method I used for testing:

I start with an empty bitcoind (Regtest mode) and Azure Storage Emulator while QBit.Ninja.Listener.Console is running (Because it is needed for initial actions for interaction with QBit.Ninja). I generate 320 transactions each about 100 KB (Less than 100 KB, exactly each transaction spends one input to one output script which is consisted of 98000 OP_0 [in order not to mess with maximum SIGOPS]) and broadcast them one by one.

When I issue "generate 1" using bitcoin-cli for some reason I get about 16 MB blocks, and not 32 MB (My configuration for max block size is either 32 or 64 MB), and the running QBit.Ninja.Listener.Console indexes it.

I am not sure about correct method of measuring spent time, so I have added
`
 var watch = System.Diagnostics.Stopwatch.StartNew();
`
at the top of `void node_MessageReceived(Node node, IncomingMessage message)` in QBitNinjaNodeListener.cs and
`watch.Stop();`
`var elapsedMs = watch.ElapsedMilliseconds;`
`System.Console.WriteLine(string.Format("[{0}]: Elapsed time in miliseconds: {1} and message payload is {2}", DateTime.Now.UnixTimestamp(), elapsedMs, message.Message.Payload.ToString()));`
At the end of method.

Everything is indexed under 1 second. The large block (16 MB) generation leads to a HeadersPayload which takes about 41 milliseconds and a BlockPayload which takes about 5xx (528, 552) milliseconds. I ran this test twice. Transaction indexation (Before block generation), each take about anything between 10-about 33 milliseconds. 

I think this kind of test has three parameters which will affect it:
1- The specification of machine, running test, specifically CPU and Memory
2- The structure of transactions (For example my test consisted of 100 KB transactions, with no sig op in output), real situation may be much more different.
3- The indexing nature (For example my test QBit.Ninja.Listener.Console was aware of all transactions before 16 MB block was generated [I am not much sure about internal logic, but I think, transactions are not indexed again, just the block space holder gets filled] and submitted for indexation, I think this is a reasonable nature also in production), since listener is always running.

Thanks for your attention

**Comment by NicolasDorier** [comment]
Thanks for trying, you should use real azure storage, not storage emulator.
What you should measure is how much time is spent into:

In `QBitNinjaListener`: Search for `IndexBlocksTask`, the relevant part is the call to `Index` method. 
Normally `IndexBlocksTask` is quick, `IndexTransactionsTask` is longer, `IndexBalanceTask` of `_LockBalance` (not the `_LockWallets` one) should be veryyyyyy slow.

IndexBlocksTask makes 1 request per block.
IndexTransactionsTask makes 1 request per transaction
IndexBalanceTask makes 1 request per input and per output.

Latency play a big role, which is why you should use real storage.

**Comment by bijakatlykkex** [comment]
I have rearranged my tests, to mine a big block (Mining code with help of Stratis project) while its transactions is not informed to bitcoind.

32 MB blocks using submitblock bitcoin-cli call led to "inconclusive" error.
16 MB block passed through.

I also added time difference calculation to top and bottom of 4 places above, the test is done using local bitcoin unlimited, hosted in Microsoft servers against real Azure storage, 3 times, the result is as following (As stated above each transaction is about 100KB, one input, one output consisting all zeros):

Elapsed time in miliseconds is: 7975 for The block index time..
Elapsed time in miliseconds is: 3932 for The transaction index time..
Elapsed time in miliseconds is: 8200 for The balance index time (lock balance)..
Elapsed time in miliseconds is: 47 for The balance index time (lock wallet)..

Elapsed time in miliseconds is: 6708 for The block index time..
Elapsed time in miliseconds is: 2928 for The transaction index time..
Elapsed time in miliseconds is: 8176 for The balance index time (lock balance)..
Elapsed time in miliseconds is: 20 for The balance index time (lock wallet)..

Elapsed time in miliseconds is: 6787 for The block index time..
Elapsed time in miliseconds is: 5671 for The transaction index time..
Elapsed time in miliseconds is: 8765 for The balance index time (lock balance)..
Elapsed time in miliseconds is: 224 for The balance index time (lock wallet)..

**Comment by NicolasDorier** [comment]
not so bad actually. I assume your block has lots of transaction and not just one big one ?

**Comment by bijakatlykkex** [comment]
The 16 MB block, includes exactly 160 transactions, each about 100 KB.

**Comment by NicolasDorier** [comment]
@bijakatlykkex this is why it was fast. Realist condition is transactions of 500 bytes. I think it will take 10 times longer.
