### ISSUE TITLE
Please provide steps to make own Qbitninja server

### ISSUE THREAD

**Issue by cryptodeveloperin** [MetacoSA/QBitNinja#36]
Hi Nic,

Please can you provide me the steps to generate own qbite ninja server. Because on github i could not get full details.

Also please can you tell me what is the downtime on Qbit public server - Main (not testnet)  Indexing

**Comment by NicolasDorier** [comment]
The time it takes indexing you mean? or the downtime?

**Comment by NicolasDorier** [comment]
I explain how to install on https://github.com/MetacoSA/QBitNinja readme.

Please google each of those parts there is tons of resources.
