### ISSUE TITLE
live Main net not working

### ISSUE THREAD

**Issue by cryptodeveloperin** [MetacoSA/QBitNinja#37]
var getCurrentBlock = client.GetBlock(new BlockFeature(SpecialFeature.Last)).Result

This throws error one more error occur. Please can you check?

**Comment by NicolasDorier** [comment]
Yes sorry, I was renewing https certificates and experienced issue doing so. This is done now, should work.

**Comment by cryptodeveloperin** [comment]
So in future this will not happen again?
Also i am relying on your API currently. So if you change HTTPS then do we need to change dll? i am using 39 version.

**Comment by NicolasDorier** [comment]
No need to change.
QBitNinja is pretty stable, in general I would say once or twice every 6 months there is temporary issues that I fix under 24H.

I advise though to people to host their own instance for production purposes. QBitNinja public servers are not meant for production (even if I am guilty of using it for production myself on some projects)

**Comment by cryptodeveloperin** [comment]
Thanks...I will create server but at this stage i could not do that.

**Comment by NicolasDorier** [comment]
You can try other paid offer (like blockcypher), but apparently they are not stable either. I have lot's of users who switched from commercial block explorer to qbitninja public servers because even if qbitninja public servers are not for production, it is still more stable than paid alternatives.
