### ISSUE TITLE
After INIT, Listen always throws: Only the genesis block can have no previous block

### ISSUE THREAD

**Issue by everyonce** [MetacoSA/QBitNinja#38]
I've done this three times, run init (on multiple machine with the same app.config and executable) - and then when it completes initial indexing, and I try to run "listen" on a single instance, it always throws this error.  Any insight?  I'm glad to provide whatever additional information I can.

**Comment by NicolasDorier** [comment]
Do you have a stacktrace?

**Comment by NicolasDorier** [comment]
In general I always hosted the front end on a Azure website, as it makes it easy to configure scaling/SSL Everywhere, never used `--Listen`. I would advise you to do the same, this is not complicated.

**Comment by everyonce** [comment]
How do you ensure your Azure Table Storage stays current without running `--Listen` ?  It seems to me that's the only thing listening to the full node (bitcoind)?

Here's the trace, the error happens on QbitNinjaNodeListener.cs line 121: `client.SynchronizeChain(chain);`
I can access runtime vars, etc, from the debugger (i think) if you're looking for anything in particular:


`System.ArgumentException occurred
  HResult=0x80070057
  Message=Only the genesis block can have no previous block
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at NBitcoin.ChainedBlock..ctor(BlockHeader header, uint256 headerHash, ChainedBlock previous)
   at NBitcoin.Indexer.ChainChangeEntryExtensions.UpdateChain(IEnumerable`1 entries, ChainBase chain)
   at NBitcoin.Indexer.IndexerClient.SynchronizeChain(ChainBase chain)
   at QBitNinja.Notifications.QBitNinjaNodeListener.Listen(ConcurrentChain chain) in D:\Programs\QBitNinja-1.0.3.44\QBitNinja\Notifications\QBitNinjaNodeListener.cs:line 121
   at QBitNinja.Listener.Console.Program.Main(String[] args) in D:\Programs\QBitNinja-1.0.3.44\QBitNinja.Listener.Console\Program.cs:line 113
`

**Comment by NicolasDorier** [comment]
I am sorry , `--Listen` is needed, I confused it with `--Web`.

**Comment by NicolasDorier** [comment]
One second, looking. Sometimes this table can get corrupt, even if rare. This is not a big deal though (no need to reindex everything, you can normally just clear the table and it will reindex it fast) I am checking.

**Comment by NicolasDorier** [comment]
Ok so try this:
Just before SynchronizeChain run this only once.
```
client.Configuration.GetChainTable().DeleteIfExists();
```
Then close the program.

You may have to wait 5 after closing so that Azure properly clean the table. Then restart again.

**Comment by everyonce** [comment]
Would it work the same just to log into Azure and delete my chain table?  (is it "chain" or "chainchache"?)

**Comment by everyonce** [comment]
this seems to have fixed it.  is the transaction table/etc still ok even if this thing dies and restarts, etc, or if i delete the chain table as needed?

**Comment by NicolasDorier** [comment]
@everyonce yes, actually the front end of QBitNinja (the QBitNinja website) already does that as you can see [here](https://github.com/MetacoSA/QBitNinja/blob/master/QBitNinja/QBitNinjaDependencyResolver.cs#L75).

It should not happen often, and has no noticeable side effect. This table is nothing more than the chain of headers, which is retrieved again and reindexed by the indexer everytimes a block is found anyway.

**Comment by everyonce** [comment]
cool, thanks for your help!!
