### ISSUE TITLE
Invaild address

### ISSUE THREAD

**Issue by cryptodeveloperin** [MetacoSA/QBitNinja#39]
Hi Nic,

When we used following address to transfer money it give me invalid key:
38DdjQuLgpPebLFKFysxvWAjWHi5vpH56r
3JPNA8vXjfkC1i8ZUXbRggjXi19jirxmLD

i have tried with follwing way:
 BitcoinAddress bitcoinAddress = new BitcoinPubKeyAddress(address, network);
also tried with:
Script receiverScriptPubKey = new BitcoinPubKeyAddress(address).ScriptPubKey;

Please let me know what is the issue? i am using version 39. 

Thanks.

**Comment by NicolasDorier** [comment]
Use `BitcoinAddress.Create` instead.

**Comment by cryptodeveloperin** [comment]
ok thanks.
