### ISSUE TITLE
transaction taking too long

### ISSUE THREAD

**Issue by cryptodeveloperin** [MetacoSA/QBitNinja#40]
Hi Nic,

some of withdrawn transaction already taken 36 hours but still not get single confirmation. IS there anything we have to do?

just an example: This is with fee of 0004
https://blockchain.info/tx/f4c94439d87eb021c49896e6def5ba8094bdd47899d85076ded6d4f32378dbe1

Also some with fee of .000975 also not get any confirmation.

**Comment by NicolasDorier** [comment]
You fees are too low https://www.smartbit.com.au/tx/f4c94439d87eb021c49896e6def5ba8094bdd47899d85076ded6d4f32378dbe1

25 satoshi per bytes, it might take [7 days](https://jochen-hoenicke.de/queue/#2w).

**Comment by NicolasDorier** [comment]
Closing as not related to QBitNinja.

**Comment by cryptodeveloperin** [comment]
ok thanks for response.
