### ISSUE TITLE
IS THERE ANY WAYS OF REPLACE-BY-FEE IN 39 VERSION

### ISSUE THREAD

**Issue by cryptodeveloperin** [MetacoSA/QBitNinja#43]
IS THERE ANY WAYS OF REPLACE-BY-FEE IN 39 VERSION.

so i can resend ,y unconfirmed transaction to make it faster confirmation?

**Comment by NicolasDorier** [comment]
A transaction need to be RBF enabled. (using `txBuilder.SetLockTIme(1)` should do the trick)
Then this transaction will be able to be double spent.

**Comment by cryptodeveloperin** [comment]
1. Currently we already transacted but not confirmed from last some days. so now we have to accelerate. so please provide the way for old transaction. Means provide the code  (c# code) or resolution.

2. If could not accelerate then is it possible to cancel those transaction then provide the code (c# code) for it.

3. Also as per dll we create transaction for each user and when we withdraw then we used their user transaction to allocate. If there any way that will transact from main account instead of each user account? Means i have 1000 users wallet key under My main network, so total balance will reflect on main network and then we can withdrawn from it?

**Comment by NicolasDorier** [comment]
1. @cryptodeveloperin if you want to unstuck a non RBF transaction, then please, use CPFP (in other words, ask the recipient of the transaction to spend the output with higher fee)

2. You can't cancel. If you are using qbit ninja, the transaction should end up disappearing from the unspent outputs list, meaning you will try to double spend it after.

3. I don't understand the question. If you are able to take user funds without their private keys, then separate the BTC accounting (stored in Database) from the actual bitcoin address balances.

**Comment by cryptodeveloperin** [comment]
1. @cryptodeveloperin if you want to unstuck a non RBF transaction, then please, use CPFP (in other words, ask the recipient of the transaction to spend the output with higher fee).
----How can i do that?  form where we can do this CPFP?

2.  I want to ask if i got 1000 transaction with small amount, but i  need to make one big withdraw transaction then if i club all 1000 then the fee is too low in my case. so do not want to do this. so is there any way in that all 1000 transaction credited, would be reflect in main account and we can send from there? Like blockchain wallet, all money credit to wallet if we used many address to request.

**Comment by cryptodeveloperin** [comment]
You can't cancel. If you are using qbit ninja, the transaction should end up disappearing from the unspent outputs list, meaning you will try to double spend it after.

what is meaning? when it would be disappear?

**Comment by NicolasDorier** [comment]
1. I don't know what the recipient of your transaction is using so I don't know.

2.  Just ask QBitNinja for unspent txout of all the addresses of your customer.

**Comment by cryptodeveloperin** [comment]
1. Lets take an example, if user used blockchain wallet, so they can do CPFP?

2. I am asking is there any parent account where all balance reflected for our underline user? means i can transfer from there to avoid too much fee?

3. I have arise this concern, because i have 1000 inputs less then .002 btc and user try to withdrawn .1 btc, so it club many inputs and if i put fee to .0005 then it will not confirmed. I want a way to transfer from main account, if possible. so is it possible?

**Comment by cryptodeveloperin** [comment]
How long it will take to disappear the transaction? so i can transfer again.

**Comment by NicolasDorier** [comment]
1. Yes they can, they just have to spend the money they received which is unconfirmed

2. There is no notion of account in bitcoin, only addresses. Knowing which address belongs to which user is the responsability of the wallet/service you are developing, the blockchain knows nothing about it.

3. The fee of a bitcoin transaction depends on its size. The size depends on how many input you are using. You are right, spending .002 outputs are going to be costly.

4. See my last reply https://github.com/MetacoSA/QBitNinja/issues/23#issuecomment-352637621

**Comment by cryptodeveloperin** [comment]
Still i am not clear.
1. How long the transaction will be appear on network, by default 24 days?
2. If we take an example of  Xapo, blockchain and other, when we receive many small inputs then also in output we can see less numbers of input for big transaction. So is there any way in our Public API, that we have multiple users wallet address (got multiple small input). But when we make output(withdrawn) of big transaction then it could be send with less fee(but confirm in next some block).
3. If we created 2000 unique address for all users on one website, and when they transfer BTC in their wallet address then it will be reflect on main account. is it possible?
4. If yes then how can make input and output settlement for this? please provide sample.
5.. If no, means we do not have any parent -> child relationship for balance. it's only combined with user unique wallet address. is it correct?

My main concern, withdrawn taking long time when we have more inputs, and it shows negativity of us. I have to make proper deposit and withdrawn process.

**Comment by cryptodeveloperin** [comment]
Is there any way to direct chat with you guy?

**Comment by NicolasDorier** [comment]
1. How long the transaction will be appear on network, by default 24 days?

Forever, as there is always at least somebody having your transaction somewhere.

Please come on https://gitter.im/MetacoSA/NBitcoin (other NBitcoin users are there) these questions are not related to QBItNinja and I don't have time to answer them.

**Comment by cryptodeveloperin** [comment]
please can you answer this:
If we take an example of Xapo, blockchain and other, when we receive many small inputs then also in output we can see less numbers of input for big transaction. So is there any way in our Public API, that we have multiple users wallet address (got multiple small input). But when we make output(withdrawn) of big transaction then it could be send with less fee(but confirm in next some block).
If we created 2000 unique address for all users on one website, and when they transfer BTC in their wallet address then it will be reflect on main account. is it possible?
If yes then how can make input and output settlement for this? please provide sample.
5.. If no, means we do not have any parent -> child relationship for balance. it's only combined with user unique wallet address. is it correct?

**Comment by NicolasDorier** [comment]
"If we take an example of Xapo, blockchain and other, when we receive many small inputs then also in output we can see less numbers of input for big transaction. " I don't understand this sentence. You receive outputs, never inputs.

**Comment by cryptodeveloperin** [comment]
My concern is if we got small input but when withdraw, it club all input and transaction become bigger. Is there any way there i can send transaction with main account?

so we have parent child relation ship for wallet here? means all address are under any main account?

**Comment by cryptodeveloperin** [comment]
take this is an example...i have put fee .002
https://blockchain.info/tx/dde75e57458aa33a96a2831d3fe485e03b446fb0dd27fc75ce3f35b1dbffbd95

**Comment by NicolasDorier** [comment]
"way there i can send transaction with main account" what a "main account"is?

Yes if you have lots of small value output you will pay a lot.

**Comment by cryptodeveloperin** [comment]
Sorry to raise many questions but my concern not clear.

Main account mean under whose we created all user wallet address. i do not found anything on document so i ask this question.

in this transaction we paid more fee but then also due to input size, it was not confirm. So is there any way in that i can transfer money from Main parent account?
https://blockchain.info/tx/dde75e57458aa33a96a2831d3fe485e03b446fb0dd27fc75ce3f35b1dbffbd95

**Comment by NicolasDorier** [comment]
If you want to unstuck your transaction use CPFP (Child pay for parent), please google that.

**Comment by cryptodeveloperin** [comment]
As i have check i need to do RBP, so please provide code for RBF for existing transaction.

**Comment by NicolasDorier** [comment]
@cryptodeveloperin you can't because your transaction is not rbf enabled.
