### ISSUE TITLE
Version 2 and also got error today morning

### ISSUE THREAD

**Issue by cryptodeveloperin** [MetacoSA/QBitNinja#47]
Hi, do QbitNinja support version 2? if yes then which is the stable version of Package we can use?

This shows version 2 while our all transaction shows version 1. 
https://www.smartbit.com.au/tx/33cea950b1e23f4465fc005400ac0c8e53e4816a644eb30cea5aeefea12799a3

I wrote because in version 2, it shows fee double instead of version 1. Like in above example it shows 57.11 on blockchain. Then also it got confirmed.
https://blockchain.info/tx/33cea950b1e23f4465fc005400ac0c8e53e4816a644eb30cea5aeefea12799a3

Please provide more details and example for git, so it's good for us to use less satoshi as fee.

**Comment by cryptodeveloperin** [comment]
Also we got one or more error occurred from package at today 2017-12-29 06:17:45.010 UTC time.

**Comment by NicolasDorier** [comment]
Version 2 is only useful if you make use OP_CSV as specified here https://github.com/bitcoin/bips/blob/master/bip-0112.mediawiki .
It has no impact on how much time it takes to validate a transaction.

**Comment by NicolasDorier** [comment]
Please open a new issue for the error you got with more feedback.
