### ISSUE TITLE
Web App: error 502 Gateway

### ISSUE THREAD

**Issue by checho1989** [MetacoSA/QBitNinja#55]
I'm trying to set up a BlockExplorer for Stratis.
I found an error when making web requests.
"502: The web server received an invalid response while acting as a gateway or as a proxy server."

The WebApp log tells me that:
"A fork has not been found, the chain stored in blue is probably different from the input provided"

I have my Web.app file configured correctly.
Could you tell me what I'm doing wrong?
Thank you!

**Comment by NicolasDorier** [comment]
I have no idea how to make QBitNinja works with stratis. They probably did it but on a separate repo, ask on their slack.

**Comment by checho1989** [comment]
I will do it. Thank you for your answer.
