### ISSUE TITLE
ERROR BROADCAST TRANSACTION

### ISSUE THREAD

**Issue by alissonsolitto** [MetacoSA/QBitNinja#58]
This library is not being updated along with the NBitcoin?

ERROR = Method not found: 'Byte[] NBitcoin.BitcoinSerializableExtensions.ToBytes(NBitcoin.IBitcoinSerializable, NBitcoin.Protocol.ProtocolVersion).

**Comment by NicolasDorier** [comment]
sorry I need to update QBitNinjaClient probably, doing now.

**Comment by alissonsolitto** [comment]
I fixed updating the dependency of NBiticoin.

**Comment by NicolasDorier** [comment]
I updated the package as well to `QBitNinja.Client.1.0.3.47` update as well.

**Comment by NicolasDorier** [comment]
it should be on nuget in 10/15min.
