### ISSUE TITLE
Transaction unconfirmed

### ISSUE THREAD

**Issue by jrmaciel** [MetacoSA/QBitNinja#59]
Please check, my transaction unconfirmed and crash

**Comment by NicolasDorier** [comment]
I don't know your transaction. The explorer is working.

**Comment by jrmaciel** [comment]
https://blockchain.info/pt/search?search=fbb85f787fe68884d52b2e4bcfc515846ac6c87d8420ea4f9376ab9b18b8f344 

I send btc and it takes too long to appear in blockchain... 
during all day long

**Comment by NicolasDorier** [comment]
I can't do anything about it.

**Comment by jrmaciel** [comment]
I send btc and it does not confirm

check pls
https://github.com/MetacoSA/QBitNinja/issues/29#issuecomment-331683220

**Comment by NicolasDorier** [comment]
The indexer works as expected and your transaction is confirmed. The indexer has no power to get your transaction confirmed once it is broadcasted.

**Comment by jrmaciel** [comment]
Look at this topic, it's the same problem.

https://github.com/MetacoSA/QBitNinja/issues/29#issuecomment-331683220

**Comment by jrmaciel** [comment]
2 transactions with crash

459f44e157b6e9f379c74156fb60ab375f8afc87cc605b5f2f354f55aadc3223
843f4c899b187800ce979ec36e55149f249ee0b88be455323a82187105188982

**Comment by NicolasDorier** [comment]
see https://github.com/MetacoSA/QBitNinja/issues/60

**Comment by NicolasDorier** [comment]
closing this... got lot's of problem but it is finally updated.

**Comment by NicolasDorier** [comment]
It should confirm fine now
