### ISSUE TITLE
Transactions stopped to be broadcasted

### ISSUE THREAD

**Issue by dayannecosta** [MetacoSA/QBitNinja#60]
the transactions dont successfully. Pls confirm your Indexer

2 transactions with fail 

459f44e157b6e9f379c74156fb60ab375f8afc87cc605b5f2f354f55aadc3223

843f4c899b187800ce979ec36e55149f249ee0b88be455323a82187105188982

**Comment by NicolasDorier** [comment]
Yes, this is a long standing issue. I advise you to use `https://www.smartbit.com.au/api` PUSH Transaction method for now. I need to take time to fix this issue.

**Comment by NicolasDorier** [comment]
I don't think so, I have not found the root cause yet.
The reset works when the indexer is stuck, but this is not the case here.

**Comment by NicolasDorier** [comment]
tryign to do something about it now.

**Comment by NicolasDorier** [comment]
The server is down. Trying to bring it up.
Updating it brought a bunch of worm's can caused by outdated tooling on the server.

**Comment by alissonsolitto** [comment]
Hello,

Any prediction to correct the problem?
If I want to create my own QBitNinja server will the problem occur?

**Comment by dayannecosta** [comment]
Hi, this problem is happening again, pls check !

**Comment by NicolasDorier** [comment]
I don't think that is the same issue. You probably did not sent enough fees. What broadcast give you back?

**Comment by jrmaciel** [comment]
yes, this is giving false positive in all transactions

Em seg, 11 de jun de 2018 às 22:17, Nicolas Dorier <notifications@github.com>
escreveu:

**Comment by dayannecosta** [comment]
the broadcast is not giving error, only a false positive I did the test in 10 addresses with high fee

Enviado do meu iPhone

Em 11 de jun de 2018, à(s) 22:17, Nicolas Dorier <notifications@github.com> escreveu:

**Comment by NicolasDorier** [comment]
I will take a look later this week. Sorry I have been busy. As a work around, you can broadcast on https://www.smartbit.com.au/api

**Comment by dayannecosta** [comment]
I discovered the problem I was giving, the blockchain only allows 26 unconfirmed transactions, now I'm sending bigger fees
thnks

**Comment by ArtjomP** [comment]
@NicolasDorier could you restart QBitNinja please, because it seems it stopped broadcasting the transactions. 
Thank you in advance

**Comment by ArtjomP** [comment]
@NicolasDorier thx it works now
