### ISSUE TITLE
tapi.qbit.ninja is not working

### ISSUE THREAD

**Issue by alissonsolitto** [MetacoSA/QBitNinja#61]
Hello,
API "tapi.qbit.ninja" is not working

**Comment by NicolasDorier** [comment]
should be better now. Got uptime problem recently. Synching a new node at same time so it happen less often in the future.

**Comment by TarasKryvko** [comment]
I have the same problem, my testnet transaction not appear on http://tapi.qbit.ninja, but it is exists on blockchain https://live.blockcypher.com/btc-testnet/address/n29jP3M6wpSS5ZvyiKXgCKeSDdPk8q6akr/

What is happening with the api?

**Comment by NicolasDorier** [comment]
Testnet has been creating big blocks like crazy (like every 5 sec or so) and got big reorgs. It seems that this time it stucked the indexer completely. Will take look today.

**Comment by dansabadas** [comment]
1st of January and it is not working! :) Vives les gillets jaunes!

**Comment by NicolasDorier** [comment]
restarted again.

**Comment by hugoventer** [comment]
Down again?

**Comment by dansabadas** [comment]
yes

**Comment by hugoventer** [comment]
@NicolasDorier thx for you work, but can you advise the issue with http://tapi.qbit.ninja/ ?

**Comment by NicolasDorier** [comment]
@hugoventer I kicked the box, seems to start again

**Comment by hugoventer** [comment]
@NicolasDorier thank you!!

**Comment by hugoventer** [comment]
@NicolasDorier down again :-(

**Comment by NicolasDorier** [comment]
pain in the ass :(

**Comment by NicolasDorier** [comment]
should be up again

**Comment by kevinattard-vme** [comment]
@NicolasDorier down again?

**Comment by NicolasDorier** [comment]
Just tried to restart again

**Comment by dmitry537** [comment]
@NicolasDorier  down again?

**Comment by alfredaoude** [comment]
@NicolasDorier I think so, it is still timing out.

**Comment by NicolasDorier** [comment]
restarted

**Comment by alfredaoude** [comment]
@NicolasDorier Thank you!

**Comment by alfredaoude** [comment]
@NicolasDorier I think it is doing it again. :(

**Comment by alissonsolitto** [comment]
You're still in error. Well at the start of the course on NBitcoin 😞

**Comment by NicolasDorier** [comment]
Pain in the ass, the server often goes down and I have no way to automatically restart it.
I should rewrite the book using NBXplorer.
