### ISSUE TITLE
How to  speedup indexing?

### ISSUE THREAD

**Issue by Jimmy987** [MetacoSA/QBitNinja#65]
_"You can run this command line on several machine concurrently to speedup indexing.
   Take a very good VM for the indexing. You can scale down once everything is synched."_

I have a singer machine for the indexing normally, it's too slow that it take a week, like in the following picture.
![20180708122245](https://user-images.githubusercontent.com/27672219/42416781-936cd040-82aa-11e8-9b1c-f52f4b389eb0.png)

I read the document that find a method to speedup indexing,
but I confuse with this step, May I get more detail about it?
Thanks in advance!

**Comment by NicolasDorier** [comment]
You just need to wait. It takes time. (Might take one week)

**Comment by Jimmy987** [comment]
_"run the same script with the same config file on another machine"_

Do I need to setup a fully sync bitcoin node again on another machine?

**Comment by NicolasDorier** [comment]
@Jimmy987 yeah, that's why I don't advise QBitNinja these days. It is way painful to get up running. [NBXplorer](https://github.com/dgarage/NBXplorer/) is 99% of time enough and does not require a full indexing.

**Comment by Jimmy987** [comment]
OK, Thanks very much!
We use QBitNinja now. It'll take a lot time to change NBXplorer, and NBXplorer don't support m-n or P2SH now. so only a way to make it running normally.

**Comment by NicolasDorier** [comment]
> NBXplorer don't support m-n or P2SH 

It does support it.
