### ISSUE TITLE
How to get a list of transaction for address?

### ISSUE THREAD

**Issue by bazooka70** [MetacoSA/QBitNinja#66]
Can I get a list of transactions for a given address using QBitNinja?

**Comment by NicolasDorier** [comment]
http://api.qbit.ninja/balances/15sYbVpRh6dyWycZMwPdxJWD4xbfxReeHe

**Comment by bazooka70** [comment]
Thanks mate! can I somehow get the tx fee for each transaction?

**Comment by NicolasDorier** [comment]
Yes, see the api here https://api.qbit.ninja/

**Comment by bazooka70** [comment]
So for each operation/tx in the `balances` I need to call `transactions/tx`?

**Comment by NicolasDorier** [comment]
Yes.

**Comment by bazooka70** [comment]
hmmmm... Isn't to possible to already include the fee in the `balances`?

**Comment by NicolasDorier** [comment]
Nop, it would kill performance for the address query.

**Comment by bazooka70** [comment]
I see. Thanks again :+1: 
BTW, any alt coins also supported for  QBitNinja?
