### ISSUE TITLE
Handling coinbase as a colored transaction unsuccessful

### ISSUE THREAD

**Issue by bijakatlykkex** [MetacoSA/QBitNinja#7]
It seems there is problem in handling coinbase as a colored transaction:

Works (not coinbase): http://tapi.qbit.ninja/transactions/270fb9c799a3892af05fa1722caa31e85282dd3573eae4eaf26d82019bf37ba1?colored=true

Doesn't work (coinbase): http://tapi.qbit.ninja/transactions/c844644e7be550fee5d45a2fa9fae0c884fcda07222017a3cb1d83212f5e82f2?colored=true (works without colored parameter)

It seems the Indexer method GetTransactionAsync is causing the problem.

**Comment by NicolasDorier** [comment]
mmmh strange I remember having fixed that : Coinbase can't be colored. Thanks for bug report, will fix it.

**Comment by NicolasDorier** [comment]
Fixed, was a bug of NBitcoin thanks !  (package and qbit updated)

https://github.com/MetacoSA/NBitcoin/commit/3619855ab5ca0d5cd06b2e378884a0ea10f1e4cd
