### ISSUE TITLE
Error in operations, balance not found

### ISSUE THREAD

**Issue by dayannecosta** [MetacoSA/QBitNinja#74]
qbit 
https://api.qbit.ninja/transactions/292ef3918d0da3fc90c4bc3657cbf4f1df07c299c6b7b605adf68f19361bd213

blockchain have balance
https://www.blockchain.com/btc/tx/292ef3918d0da3fc90c4bc3657cbf4f1df07c299c6b7b605adf68f19361bd213

**Comment by dayannecosta** [comment]
it takes about 30 minutes to appear in the transaction qbit

**Comment by NicolasDorier** [comment]
Seems fine now

**Comment by NicolasDorier** [comment]
I should have fixed all issues.
