### ISSUE TITLE
http://tapi.qbit.ninja/ not working when retreiving balances and pushing transactions to network

### ISSUE THREAD

**Issue by Grey007** [MetacoSA/QBitNinja#76]
Hi,

Unable to retrieve latest balances, and push new transactions to the network.

**Comment by NicolasDorier** [comment]
I restarted the indexer, hopefully fixed in 10min

**Comment by Grey007** [comment]
Seems like the API not working at all at the moment

**Comment by NicolasDorier** [comment]
now?

**Comment by Grey007** [comment]
Working now. Thanks.
