### ISSUE TITLE
cant connect to stratis bitcoind

### ISSUE THREAD

**Issue by alfhv** [MetacoSA/QBitNinja#77]
it is possible to use qbitninja with a stratis.bitcoind server ?? 
I can't get connection, I receive error: "The node is not in a connected state" when calling node.VersionHandshake.
already tried with same config file with bitcoind and it is ok.
thanks

**Comment by NicolasDorier** [comment]
it is not

**Comment by alfhv** [comment]
thanks nicolas, can you give me some technical explanation around to better understand ? it is due to non implemented feature or just incompatible architecture ? thanks again.

**Comment by NicolasDorier** [comment]
It is like if you asked me if ETH was supported by QBitNinja. It is not, this is a separate currency. I think stratis made their own fork of qbit, you need to ask them.

**Comment by alfhv** [comment]
I'm talking about Stratis.BitcoinD (Bitcoin node implementation) not StratisD(which of course is a very diferent network and currency)
is your reply still accurate in this case (BitcoinD !) ???  thanks
