### ISSUE TITLE
unspentonly output not updated

### ISSUE THREAD

**Issue by bijakatlykkex** [MetacoSA/QBitNinja#8]
Hello,

While an unconfirmed transaction http://api.qbit.ninja/transactions/43eaab5060bd2ba614b1839f1e47662be267d0135a81ed3bd6535e0a605484f3 has spent an output (40feb5d2615af9261070989c4ef5bdadfe40598042b53da8f24953a3d1ac87e6 index 1) this is listed as unspent (http://api.qbit.ninja/balances/38CPJmQaWVsVka6bzEgafgZqSuJQazEjML?unspentonly=true)

[transaction.txt](https://github.com/MetacoSA/QBitNinja/files/278231/transaction.txt)
[unspent.txt](https://github.com/MetacoSA/QBitNinja/files/278232/unspent.txt)

**Comment by NicolasDorier** [comment]
interesting, looking at it.

**Comment by NicolasDorier** [comment]
I don't see it in http://api.qbit.ninja/balances/38CPJmQaWVsVka6bzEgafgZqSuJQazEjML?unspentonly=true

**Comment by NicolasDorier** [comment]
What could have happened is the following: If the transaction take time to be confirmed then the unspentOnly "forgot" the spending. This is done for preventing stuck coins to never be redeemed. 
Can it be the case ?

**Comment by bijakatlykkex** [comment]
Yes, it seems it could happen, if the described behavior is present in the code. The current transaction has OP_RETURN output (it is open assets) and it seems some miners do not mine transactions with such output well.

But could this forget time be configured somehow? Since in short time when nodes has not forgotten the transaction, this could create possible double spend.

**Comment by NicolasDorier** [comment]
mmh actually the expiration time is 30 minutes, this seems wrong I thought I've put much more.
I can increase the time to 6 hours. Making it configurable is possible, but in my mind a big enough expiration should be just enough.

**Comment by bijakatlykkex** [comment]
Thanks. If you don't mind, would you please point me to the source code line?

**Comment by bijakatlykkex** [comment]
In main net, open assets transactions take more than a day to get confirmation.

**Comment by NicolasDorier** [comment]
https://github.com/MetacoSA/QBitNinja/commit/919a17a7cb517971fcfebe1f1f1c7fe59c234db2

I'll update the servers today.
More than a day for a confirmation ? can you point me out on such transaction ? it should not take so long.

**Comment by bijakatlykkex** [comment]
All those transactions has got confirmation now. I will notify you when I encountered such a transaction.

**Comment by NicolasDorier** [comment]
I updated the servers. Open Asset transactions should not take a day to get a confirmation, we need to find out why.

**Comment by bijakatlykkex** [comment]
For example check this: https://www.blocktrail.com/BTC/tx/da8988400f2460d068f9d34a53441b42edcdd223aa62dc25451c4e54a44e0164?txoutIdx=1 it has been confirmed after more than 17 hours.

The reason behind this may 2 things, a- the OP_RETURN output itself (some do not like this type of transaction for example https://blockchain.info/pushtx does not broadcast OP_RETURN transactions as far as I remember, so fewer miner may mine the transaction: https://bitcointalk.org/index.php?topic=391491.10;wap2). b- The OP_RETURN bitcoin value is 0 , this could be considered as dust.

**Comment by NicolasDorier** [comment]
no, I think the reason is that 600 satoshi is considered dust for some nodes. (at one point the dust amount was bump for preventing spam attack)

You should try to use more than 600 satoshi. I'm using 2500 satoshi by default with NBitcoin now.

OP_RETURN with 0 as value is not considered dust for bitcoin core.

**Comment by bijakatlykkex** [comment]
I think coinprism.com still uses 600 satoshi as Bearer coin for colored coins.

**Comment by NicolasDorier** [comment]
@bijakatlykkex you seem to use NBitcoin and qbitninja, why do you use coinprism API for sending your transactions ?

**Comment by bijakatlykkex** [comment]
Coinprism seems to be from original Open Assets developer and is used as a reference, and becoming independent of it, will be in gradual steps.

Thank you for supporting Open Assets in NBitcoin.
