### ISSUE TITLE
QBitNinja.Listener.Console.exe closed

### ISSUE THREAD

**Issue by jrmaciel** [MetacoSA/QBitNinja#81]
After the run **QBitNinja.Listener.Console.exe --init** 
i'm running **QBitNinja.Listener.Console.exe** and close the console...

https://btccmd.azurewebsites.net/balances/167khjpwsNLUDaD1y8QtRCg6xvXkr1vNG3/summary

It has only 9 transactions and there are 49 transactions for this address

**Comment by jrmaciel** [comment]
Problema resolved! 

After the run QBitNinja.Listener.Console.exe --init
run QBitNinja.Listener.Console.exe **--Listen**

Please correct in readme.md

**Comment by NicolasDorier** [comment]
Thanks, just updated
