### ISSUE TITLE
Older versions built against .Net Framework v4.7, rendering them unusable with stated .Net dependency.

### ISSUE THREAD

**Issue by bcpfl** [MetacoSA/QBitNinja#83]
Previous QBitNinja versions such as 1.0.3.45, 1.0.3.44 and 1.0.3.43  (all with a stated .Net Framework dependency of 4.5), cannot be resolved when using them in projects with .Net versions 4.5.2 (or earlier).  The error message from VS is:
The primary reference "QBitNinja.Client, Version=1.0.3.44, Culture=neutral, processorArchitecture=MSIL" could not be resolved because it was built against the ".NETFramework,Version=v4.7" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.5.2".

**Comment by NicolasDorier** [comment]
so https://www.nuget.org/packages/QBitNinja.Client/ is supported 452, 461, standard1.1.

Are you using nuget?

**Comment by bcpfl** [comment]
Yes, in VS 2105, using the NuGet Package Manager, I select  QBitNinja.Client version v.1.0.3.45 which indicates a .Net Framework reference of 4.5 (same with v1.0.3.44 and v1.0.3.43).  I assumed, perhaps mistakenly, that these would be compatible in a project targeting .Net Framework 4.5.2.  But upon compilation I received the error noted in my original message.

However QBitNinja.Client v1.0.3.47 explicitly indicates that one of the supported frameworks is .Net 4.5.2, and does compile without any problems.  So this issue is not really a problem.  But I am still unsure why previous versions (1.0.3.45, ...) would not work, and why the error would indicate that they were built against .Net v4.7.

Thanks!

**Comment by NicolasDorier** [comment]
I dropped support from .46 to .NET 4.5. Now supporting from .NET 4.5.2 that's the only change.

Your project is probably not using 4.5.2. (by default VS2015 don't)

**Comment by bcpfl** [comment]
OK, not a problem.  I was just wondering about the error message's reference to .Net v4.7.

Thanks for the great project(s) and support!
