### ISSUE TITLE
service is anavailable

### ISSUE THREAD

**Issue by FIVIL** [MetacoSA/QBitNinja#84]
Hi, since today the QBitNinjaClient doesnt work due to a sever error the url https://tapi.qbit.ninja keep sending 500 error
is it gonna be Ok sometimes soon or should we migrate to another provider

**Comment by NicolasDorier** [comment]
strange, will take a look.

**Comment by NicolasDorier** [comment]
it is back up after a restart. First time it happens to me. If it happen again, I will investigate.

**Comment by FIVIL** [comment]
Hi, the same thing happened again, so i was wondering if you could restart the server again please.
And also considering this happens sometimes i was wondering is it possible to use qbitninja but with other service provider rather than yours without changing my code entirly?
Tbx

**Comment by NicolasDorier** [comment]
Well, you can host qbit ninja for yourself.

**Comment by NicolasDorier** [comment]
yes, follow the README
