### ISSUE TITLE
QBitNinja.GetBalance Server Issue

### ISSUE THREAD

**Issue by john-bal** [MetacoSA/QBitNinja#87]
Greetings,
i have a website which uses asp.net request to check bitcoin balance using QBitNinja library.

//c#
Client_QBitNinja.GetBalance(new BitcoinPubKeyAddress(PublicKey), true).Result;

Now this works fine on my locally installed IIS

when i upload the application to my host server it generates exception error as follows:

System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 23.102.12.43:443

any idea how to solve it?

**Comment by NicolasDorier** [comment]
Should work now, I restarted the servers.

**Comment by john-bal** [comment]
Thanks , it apparently seems a problem related to my hosting server provider , BECAUSE it works fine on my pc +  it works fine on a free hosting server . It only generates exception error on my main hosting provider (!&1 Ionos)

**Comment by john-bal** [comment]
May i ask the proxy address of the QBitNinja so i can include it in my config file ?

**Comment by NicolasDorier** [comment]
just pass the URL as HTTPS in `new QBItNinjaClient`.

**Comment by NicolasDorier** [comment]
https://api.qbit.ninja/
