### ISSUE TITLE
How to check balance of Multi Signature Wallet?

### ISSUE THREAD

**Issue by LeetGod** [MetacoSA/QBitNinja#89]
I can easily check the balance of a regular single key bitcoin address, but how for multi-signature wallets?

Such as: 3P3QsMVK89JBNqZQv5zMAKG8FK3kJM4rjt

I get the error: 

Invalid BitcoinPubKeyAddress

**Comment by NicolasDorier** [comment]
copy and paste your code here.

**Comment by undergod11** [comment]
```
            Dim net As Network = Network.Main
            Dim transaction = New Transaction()
            Dim bitcoinPrivateKey = New BitcoinSecret(PrivateKey)
            Dim fromAddress = bitcoinPrivateKey.GetAddress().ToString()
            Dim addressBalance As Decimal = 0
            Dim addressBalanceConfirmed As Decimal = 0
            Dim ConfirmedBalance As Decimal = MssGetBalance(fromAddress, True, addressBalance, addressBalanceConfirmed)

            Dim client As QBitNinjaClient = New QBitNinjaClient(net)
            Dim balance = client.GetBalance(New BitcoinPubKeyAddress(fromAddress), True).Result
```

The error is on:

Dim balance = client.GetBalance(New BitcoinPubKeyAddress(fromAddress), True).Result

**Comment by NicolasDorier** [comment]
`BitcoinAddress.Create(fromAddress, Network.Main)`

**Comment by undergod11** [comment]
Thank you!  It works now

Also, I'm using the old way to build a transaction.

![image](https://user-images.githubusercontent.com/19926248/53284063-878b6580-3703-11e9-9be1-4aa14dd686c3.png)

But  Dim transaction = New Transaction.Create(net) isn't working for me

**Comment by NicolasDorier** [comment]
It says `Transaction.Create(net);`
