### ISSUE TITLE
Http 500 error in balances summary

### ISSUE THREAD

**Issue by bijakatlykkex** [MetacoSA/QBitNinja#9]
Hello,

http://tapi.qbit.ninja/balances/2Mx3TZycg4XL5sQFfERBgNmg9Ma7uxowK9y/summary returns http 500 but http://tapi.qbit.ninja/balances/2Mx3TZycg4XL5sQFfERBgNmg9Ma7uxowK9y normally returns.

**Comment by NicolasDorier** [comment]
yes, don't expect such transaction to have a working summary with 158000 tx.
Basically /balances/address will returns after some timeout, and give you a "continuationtoken" in the request to fetch the rest.

However, for calculating /balances/summary, I need to fetch out all the transactions from the DB and make the balance calculation. (then I cache it) If there is 150 000 transaction then it will just timeout.

I don't intend to fix that in the near term as it concern a minority of addresses.

**Comment by bijakatlykkex** [comment]
Thanks for clarification.
