### ISSUE TITLE
Question: Is init phase required?

### ISSUE THREAD

**Issue by alexb5dh** [MetacoSA/QBitNinja#91]
For project I'm working right now I'm interested only in transactions happening after project is launched/released.
Do I need to wait for initial indexing in this case? Or maybe just waiting for _bitcoind_ to sync would be enough and than I can proceed directly to listening?

**Comment by NicolasDorier** [comment]
yeah you need full indexing, the init phase is needed on top of Bitcoind sync.
I advise you using blockstream esplora instead of QBitNinja. They are easier to deploy.

**Comment by alexb5dh** [comment]
Thanks for the reply.
Does esplora have anything similar to QBitNinja wallets? I need it to quickly find balance of multiple addresses.

**Comment by NicolasDorier** [comment]
@alexb5dh the wallet API is not very well tested to be honest.
If you want HD wallet I advise you to look https://github.com/dgarage/NBXplorer . It has a very simple API, does not require full indexing, and work on pruned mode. I am using it for BTCPay Server so it is pretty solid.

**Comment by alexb5dh** [comment]
NBXplorer seems like the tool I was looking for.
Thank you for the help and for supporting these libraries!
