### ISSUE TITLE
Query by Address

### ISSUE THREAD

**Issue by Ciborg2991** [MetacoSA/QBitNinja#95]
Hi. Is there a way to query a tx_id based on the address of a transaction?
I figure out that iterating over the list retrieved by the code below, in the last position, I get the tx_id, but still doesn't understand if this is the right way to do this.

`client.GetBalance(bitcoinSecret.GetAddress()).Result.Operations;`

The purpose of this is, given an private key only, query the transaction generate to the address related with the public key of this private key, to spend this transaction...
Thank you very much.

**Comment by NicolasDorier** [comment]
I don't understand your question. A transaction does not have an address. If you want to query just a txid use `client.GetTransaction`
