### ISSUE TITLE
Skipped transaction

### ISSUE THREAD

**Issue by ArtjomP** [MetacoSA/QBitNinja#96]
Hello there!
I can't get unconfirmed transaction for an address.
TxId & P2SH you can find in the code down below:
```cs
var address = "3Pyowu3xwCfJFMemKNfYJNYzzC9jD9Z2v6";
var network = Network.Main;
var destination = BitcoinAddress.Create(address, network);
var client = new QBitNinjaClient(network);
var balanceModel = await client.GetBalance(destination, false);
Assert.Contains(balanceModel.Operations, 
	o => o.Key == "d7bef280fa4a76bdb14009c1c86602456f8b54fb75fdb0979bdf1bd066350121");
```
The transaction is from this address & skipped in the operations. Here you can find it: https://chain.so/a/kmw5v-u 

Thank you in advance!

**Comment by ArtjomP** [comment]
Not when transaction is confirmed it works :(

**Comment by NicolasDorier** [comment]
The transaction disappear from qbitninja if it was not confirmed for long.

**Comment by ArtjomP** [comment]
Could I see such transactions somehow with QBitNinja?

**Comment by NicolasDorier** [comment]
yes `http://api.qbit.ninja/balances/15sYbVpRh6dyWycZMwPdxJWD4xbfxReeHe?unconfExpiration=48` for example, will show the unconf having less than 48H  instead of 24H.

**Comment by ArtjomP** [comment]
Thank you! 
Have a great day!
