### ISSUE TITLE
Server Error in '/' Application.

### ISSUE THREAD

**Issue by kepikoi** [MetacoSA/QBitNinja#98]
I've set up everything according to the documentatation and sync'd to my storage account via 5 VMs over the weekend. Deployed the webapp via VS publishing profile with Web.config settings taken from App.config but still can't get the frontend to work.  When trying to call the web app, an error 500 is returned after ca. 2 minutes. I'm getting this log from azure processes: 
![image](https://user-images.githubusercontent.com/12378498/59699393-cc2a9780-91f1-11e9-8c88-55fcd322f915.png)

Any clue what might be causing it? I've restarted the app a few times and also tried scaling up - still nothing.

Thanks

**Comment by kepikoi** [comment]
I redeployed with VS and the WebApp showed up. Another question: what app service plan are you using for http://api.qbit.ninja / http://tapi.qbit.ninja. Running on S1 yields really low response times (up to 2 minutes for a utxo query (e.g. /balances/15sYbVpRh6dyWycZMwPdxJWD4xbfxReeHe?unspentonly=true)

**Comment by NicolasDorier** [comment]
I advise `D1 v2`. Though long reponse time may come from something else.

I use `Testnet (B3: 1)` on my side using mainnet and testnet at same time there.

**Comment by NicolasDorier** [comment]
Also make sure your vm is in the same Location as your storage!

**Comment by kepikoi** [comment]
> Also make sure your vm is in the same Location as your storage!

Thanks for the heads up! I learned this is especially important since additional costs will incure for the inter-regional bandwidth usage in azure.

Is it possible to run multiple vm instances with `QBitNinja.Listener.Console.exe --Listen` in terms of a failover strategy?

**Comment by NicolasDorier** [comment]
@kepikoi yes you can, though I never tested it, the underlying architecture should support it.

**Comment by kepikoi** [comment]
Cool! I'm running two instances right now and it seems to work just fine. I didn't notice any easing on the first VM after the second one became active, but that can have different causes.

Also the testnet instance seems to push really hard on the CPU for some reason:
![image](https://user-images.githubusercontent.com/12378498/59918259-7558d400-9424-11e9-8883-148b186eb03e.png)

One last question - what happens with the intermediate blocks / txs if all listeners stop and get resumed eventuelly. Do the missed entities get processed after the fact?

**Comment by NicolasDorier** [comment]
yes, missed entities get processed.
For the CPU, if you can find out what is taking much, it would be helpful.

The indexing process is idempotent, if you run two instances, they basically just index the same thing twice.

**Comment by kepikoi** [comment]
I could not find a way to diagnose the cause of the high CPU load on the testnet instance but I see that over weekend the process settled back to normal.

A small issue that I found with running multiple listeners in parallel is that unconfirmed utxos appear multiple times on the balances endpoint (e.g. https://qbn9931084e322ec3bd.azurewebsites.net/balances/15sYbVpRh6dyWycZMwPdxJWD4xbfxReeHe?unspentonly=true). Once the transaction is confirmed, the redundancy no longer occur.

**Comment by NicolasDorier** [comment]
ok I will need to fix this.

**Comment by kepikoi** [comment]
Cool, Let me know if you need my assistance. I could provide you access to my api instance in a pm so you that can see the issue in effect

**Comment by NicolasDorier** [comment]
@kepikoi  can you try latest commit? I should have fixed it properly.
